/* AUTO-GENERATED by scripts/sync-juce-frontend.mjs — do not edit.
 *
 * Hand-maintained types for JUCE's JavaScript frontend library, which ships
 * without any. Keep in step with the JUCE version pinned in
 * cmake/Dependencies.cmake.
 */

/** A JUCE ListenerList. addListener returns an opaque id for removeListener. */
export interface ListenerList {
  addListener(fn: (payload?: unknown) => void): number;
  removeListener(id: number): void;
  callListeners(payload?: unknown): void;
}

export interface SliderProperties {
  start: number;
  end: number;
  skew: number;
  name: string;
  label: string;
  numSteps: number;
  interval: number;
  parameterIndex: number;
}

export interface SliderState {
  readonly name: string;
  readonly identifier: string;
  readonly properties: SliderProperties;
  readonly valueChangedEvent: ListenerList;
  readonly propertiesChangedEvent: ListenerList;
  /** Value in [0, 1], matching AudioProcessorParameter::getValue(). */
  setNormalisedValue(newValue: number): void;
  /** Call before the first setNormalisedValue of a drag. */
  sliderDragStarted(): void;
  /** Call after the last setNormalisedValue of a drag. */
  sliderDragEnded(): void;
  getNormalisedValue(): number;
  getScaledValue(): number;
}

export interface ToggleProperties {
  name: string;
  parameterIndex: number;
}

export interface ToggleState {
  readonly name: string;
  readonly identifier: string;
  readonly properties: ToggleProperties;
  readonly valueChangedEvent: ListenerList;
  readonly propertiesChangedEvent: ListenerList;
  getValue(): boolean;
  setValue(value: boolean): void;
}

export interface ComboBoxProperties {
  name: string;
  parameterIndex: number;
  choices: string[];
}

export interface ComboBoxState {
  readonly name: string;
  readonly identifier: string;
  readonly properties: ComboBoxProperties;
  readonly valueChangedEvent: ListenerList;
  readonly propertiesChangedEvent: ListenerList;
  getChoiceIndex(): number;
  setChoiceIndex(index: number): void;
}

export function getSliderState(name: string): SliderState;
export function getToggleState(name: string): ToggleState;
export function getComboBoxState(name: string): ComboBoxState;

/** Calls a function registered with Options::withNativeFunction() in C++. */
export function getNativeFunction(
  name: string,
): (...args: unknown[]) => Promise<unknown>;

/** Rewrites a relative path to one the plugin's resource provider serves. */
export function getBackendResourceAddress(path: string): string;

/**
 * Reports the parameter under the mouse to the host, so a DAW can highlight
 * the matching automation lane. Wire it up in Phase 6.
 */
export class ControlParameterIndexUpdater {
  constructor(controlParameterIndexAnnotation: string);
  handleMouseMove(event: MouseEvent): void;
}
