/**
 * The opening growl.
 *
 * SYNTHESISED, NOT A SAMPLE. A .wav would be a hundred kilobytes embedded in
 * every binary for a sound that plays for three quarters of a second, and it
 * would have to be generated by the same DSP reasoning anyway. This is nine
 * nodes and no asset.
 *
 * AND IT PLAYS IN THE WEBVIEW. Nothing here touches `processBlock` — a sound
 * emitted from the plugin's output would land in whatever the host is
 * recording, go through the mixer, and be heard by everyone on the session,
 * because somebody opened a window. This reaches the system output and
 * cannot reach the DAW's audio path.
 *
 * The shape is the instrument's own: a saw through a band-pass swept like a
 * formant, with a second one a fifth below, hard-gated twice so it reads as
 * a growl rather than a swell.
 */

/** Short. A splash that outlasts the window opening is one people learn to
    dread. */
const DURATION_SECONDS = 0.75;

export async function playGrowl(): Promise<void> {
  const AudioContextClass =
    window.AudioContext ??
    (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;

  if (!AudioContextClass) return;

  let context: AudioContext;

  try {
    context = new AudioContextClass();
  } catch {
    return;
  }

  /*  A webview may block audio until a gesture, and opening a plugin window
      is not one. Resuming is best effort: a silent splash is fine, an
      exception thrown into React's render is not. */
  try {
    if (context.state === 'suspended') await context.resume();
  } catch {
    /* ignore */
  }

  if (context.state !== 'running') {
    void context.close();
    return;
  }

  const now = context.currentTime;
  const end = now + DURATION_SECONDS;

  const output = context.createGain();
  output.gain.value = 0.18; // Quiet. It is a flourish, not an alert.
  output.connect(context.destination);

  /*  The gate: two hard steps, which is what separates a growl from a
      filter sweep. Same reasoning as the riddim presets' stepped curves —
      the rhythm is the shape, not the rate. */
  const gate = context.createGain();
  gate.gain.setValueAtTime(0, now);
  gate.gain.linearRampToValueAtTime(1, now + 0.02);
  gate.gain.setValueAtTime(1, now + 0.2);
  gate.gain.linearRampToValueAtTime(0.15, now + 0.22);
  gate.gain.setValueAtTime(0.15, now + 0.3);
  gate.gain.linearRampToValueAtTime(1, now + 0.32);
  gate.gain.setValueAtTime(1, now + 0.55);
  gate.gain.exponentialRampToValueAtTime(0.0001, end);
  gate.connect(output);

  // The vowel. Swept across the range a formant filter would cover, which is
  // what makes it read as a voice rather than as a synth tone.
  const formant = context.createBiquadFilter();
  formant.type = 'bandpass';
  formant.Q.value = 6;
  formant.frequency.setValueAtTime(320, now);
  formant.frequency.exponentialRampToValueAtTime(1500, now + 0.28);
  formant.frequency.exponentialRampToValueAtTime(420, now + 0.6);
  formant.connect(gate);

  // Some of the dry signal past the band-pass, or the low end vanishes -
  // exactly the insertion loss the plugin's own formant filter has.
  const body = context.createGain();
  body.gain.value = 0.35;
  body.connect(gate);

  const oscillators: OscillatorNode[] = [];

  for (const frequency of [55, 82.5]) {
    const oscillator = context.createOscillator();
    oscillator.type = 'sawtooth';
    oscillator.frequency.value = frequency;

    // A slight downward bend, which is most of why a growl sounds like it is
    // being pushed rather than played.
    oscillator.frequency.setValueAtTime(frequency * 1.06, now);
    oscillator.frequency.exponentialRampToValueAtTime(frequency, now + 0.25);

    oscillator.connect(formant);
    oscillator.connect(body);
    oscillator.start(now);
    oscillator.stop(end + 0.05);

    oscillators.push(oscillator);
  }

  // Close the context rather than leaking one per window open.
  window.setTimeout(() => {
    for (const oscillator of oscillators) oscillator.disconnect();
    void context.close();
  }, (DURATION_SECONDS + 0.2) * 1000);
}
