#include "Modulation.h"

#include "../params/ParameterIDs.h"

namespace gnarl::dsp
{

namespace
{
    /**
        The one table.

        The enum value, the parameter ID and the display name live in the same
        row, so they cannot drift apart - which they would if they were three
        separate switch statements. Generated by hand into this shape once;
        adding a destination is one row plus one case in applyOffsets.
    */
    struct DestinationEntry
    {
        ModDestination destination;
        const char* parameterID;
        const char* displayName;
    };

    constexpr DestinationEntry kDestinations[] = {
        { ModDestination::osc1TablePosition,    pid::osc[0].tablePos,         "Osc 1 Position" },
        { ModDestination::osc1WarpAmount,       pid::osc[0].warpAmount,       "Osc 1 Warp" },
        { ModDestination::osc1Level,            pid::osc[0].level,            "Osc 1 Level" },
        { ModDestination::osc1Pan,              pid::osc[0].pan,              "Osc 1 Pan" },
        { ModDestination::osc1PitchSemi,        pid::osc[0].pitchSemi,        "Osc 1 Semi" },
        { ModDestination::osc1PitchFine,        pid::osc[0].pitchFine,        "Osc 1 Fine" },
        { ModDestination::osc1UnisonDetune,     pid::osc[0].unisonDetune,     "Osc 1 Detune" },
        { ModDestination::osc1GrainSize,        pid::osc[0].grainSize,        "Osc 1 Grain Size" },
        { ModDestination::osc1GrainDensity,     pid::osc[0].grainDensity,     "Osc 1 Grain Density" },
        { ModDestination::osc2TablePosition,    pid::osc[1].tablePos,         "Osc 2 Position" },
        { ModDestination::osc2WarpAmount,       pid::osc[1].warpAmount,       "Osc 2 Warp" },
        { ModDestination::osc2Level,            pid::osc[1].level,            "Osc 2 Level" },
        { ModDestination::osc2Pan,              pid::osc[1].pan,              "Osc 2 Pan" },
        { ModDestination::osc2PitchSemi,        pid::osc[1].pitchSemi,        "Osc 2 Semi" },
        { ModDestination::osc2PitchFine,        pid::osc[1].pitchFine,        "Osc 2 Fine" },
        { ModDestination::osc2UnisonDetune,     pid::osc[1].unisonDetune,     "Osc 2 Detune" },
        { ModDestination::subLevel,             pid::sub.level,               "Sub Level" },
        { ModDestination::noiseLevel,           pid::noise.level,             "Noise Level" },
        { ModDestination::filter1Cutoff,        pid::filter[0].cutoff,        "Filter 1 Cutoff" },
        { ModDestination::filter1Resonance,     pid::filter[0].resonance,     "Filter 1 Res" },
        { ModDestination::filter1Drive,         pid::filter[0].drive,         "Filter 1 Drive" },
        { ModDestination::filter1Mix,           pid::filter[0].mix,           "Filter 1 Mix" },
        { ModDestination::filter1FormantX,      pid::filter[0].formantX,      "Filter 1 Vowel X" },
        { ModDestination::filter1FormantY,      pid::filter[0].formantY,      "Filter 1 Vowel Y" },
        { ModDestination::filter1FormantThroat, pid::filter[0].formantThroat, "Filter 1 Throat" },
        { ModDestination::filter2Cutoff,        pid::filter[1].cutoff,        "Filter 2 Cutoff" },
        { ModDestination::filter2Resonance,     pid::filter[1].resonance,     "Filter 2 Res" },
        { ModDestination::filter2Drive,         pid::filter[1].drive,         "Filter 2 Drive" },
        { ModDestination::filter2Mix,           pid::filter[1].mix,           "Filter 2 Mix" },
    };
}

ModDestination getDestinationForParameterID (const juce::String& parameterID)
{
    // MESSAGE THREAD only: this compares strings. The audio thread uses the
    // resolved enum, which is the whole reason the resolution happens here.
    for (const auto& entry : kDestinations)
        if (parameterID == entry.parameterID)
            return entry.destination;

    // An unknown ID is not an error. A preset saved against a later version,
    // or one naming a parameter since retired, should load with that slot
    // inert rather than refusing to load at all.
    return ModDestination::none;
}

juce::String getParameterIDForDestination (ModDestination destination)
{
    for (const auto& entry : kDestinations)
        if (entry.destination == destination)
            return entry.parameterID;

    return {};
}

juce::String getDestinationDisplayName (ModDestination destination)
{
    if (destination == ModDestination::none)
        return "-";

    for (const auto& entry : kDestinations)
        if (entry.destination == destination)
            return entry.displayName;

    return "-";
}

juce::StringArray getAllDestinationDisplayNames()
{
    juce::StringArray names;
    names.add ("-");

    for (const auto& entry : kDestinations)
        names.add (entry.displayName);

    return names;
}

} // namespace gnarl::dsp
