#!/usr/bin/env python3
"""The DRUMS tab's templates, from the measured reference drums.

    python3 tools/drum_templates.py   # references/drums.json -> ui/src/drums/templates.json

measure_drums.py gives, per drop, a probability per 48th of a bar for kick,
snare and hat, and the sound of each. This turns every drop it could phase
(a kick on the bar's first tick in at least half its bars) into a template
the page plays from (docs/design/phase4-06-drums-riddimize.md):

- Beat 3 is the snare, and every template has it. Where beat 3 ALSO
  measured as a kick (its sub rises 4 dB or more with the bass playing:
  phompy, WARLORD's Snazz, 2 PHONES, thirty6ix), the snare there is layered
  with a kick's punch, and the kick row keeps that tick, so GNARL's loop
  layers its kick under the snare too. Where it measured as a plain snare
  (WARLORD's Mr Snazzy, SPACE EXPLORERS), it stays a plain snare.
- Each row is put on the grid that holds more of its hits: straight 16ths
  (every 3rd tick) or triplet 8ths (every 4th). A hit within one tick of a
  grid point moves there (a laid-back kick at tick 13 is beat 2's); further
  than that it is dropped.
- The sound numbers are carried over as they were measured.
"""

import json
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
TICKS = 48
SNARE_TICK = 24


def short(name):
    name = re.sub(r'\.(mp3|wav|flac)$', '', name, flags=re.I)
    name = re.sub(r'_?(free|freebie|free_download|direct_download|free_dl)\b.*$', '', name, flags=re.I)
    return re.sub(r'[_\s]+', ' ', name).strip()[:32]


def to_grid(prob):
    """(grid name, steps) for the grid that keeps more of the row's mass."""
    best = None
    for name, step in (('straight', 3), ('triplet', 4)):
        steps = [0.0] * (TICKS // step)
        kept = 0.0
        for t, p in enumerate(prob):
            if p <= 0:
                continue
            g = round(t / step)
            if abs(g * step - t) <= 1:
                g %= len(steps)
                steps[g] = max(steps[g], p)
                kept += p
        if best is None or kept > best[2] + 1e-9:
            best = (name, steps, kept)
    return best[0], [round(v, 2) for v in best[1]]


def main():
    data = json.load(open(os.path.join(ROOT, 'references', 'drums.json')))
    out = []
    for track in data['tracks']:
        for i, drop in enumerate(track['drops']):
            p = {k: list(v) for k, v in drop['patterns'].items()}
            if p['kick'][0] < 0.5:
                continue  # not phased on its kick: the grid would be a guess
            p['snare'][SNARE_TICK] = 1.0
            rows = {}
            for k in ('kick', 'snare', 'hat'):
                grid, steps = to_grid(p[k])
                rows[k] = {'grid': grid, 'steps': steps}
            out.append({
                'name': short(track['file']) + (f' {i + 1}' if len(track['drops']) > 1 else ''),
                'bpm': track['bpm'],
                'rows': rows,
                'sound': drop['sound'],
            })
    path = os.path.join(ROOT, 'ui', 'src', 'drums', 'templates.json')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        json.dump({'_comment': 'Generated by tools/drum_templates.py from references/drums.json. Do not edit.',
                   'templates': out}, f, indent=1)
    for t in out:
        row = lambda r: ''.join('#' if v >= 0.6 else '+' if v >= 0.3 else '.' for v in r['steps'])  # noqa: E731
        print(f"{t['name']:34s} K[{t['rows']['kick']['grid'][0]}] {row(t['rows']['kick']):16s} "
              f"S[{t['rows']['snare']['grid'][0]}] {row(t['rows']['snare']):16s} H[{t['rows']['hat']['grid'][0]}] {row(t['rows']['hat'])}")
    print(len(out), 'templates')


if __name__ == '__main__':
    main()
