/**
    Dumps every factory wavetable as a compact harmonic spectrum, for the UI.

    WHY SPECTRA RATHER THAN SAMPLES. A waveform display needs whatever
    resolution its canvas happens to be, and it needs to redraw when the warp
    changes. Shipping samples would mean picking a resolution up front and
    shipping several times more data; shipping harmonics lets the UI synthesise
    the waveform at exactly the width it is drawing, and it is what the engine
    generates the table from in the first place.

    The spectra are ANALYSED BACK OUT of the generated tables rather than taken
    from the generators directly. That guarantees the display shows what the
    oscillator actually plays, including the band-limiting, rather than what
    the generator intended.

    Quantised to int8 and base64'd into a TypeScript module. 20 tables x 32
    frames x 64 harmonics x 2 bytes is about 80 KB, which is acceptable for
    something embedded in the plugin binary rather than downloaded.
*/
#include "dsp/WavetableLibrary.h"

#include <juce_dsp/juce_dsp.h>
#include <juce_events/juce_events.h>

#include <cmath>
#include <cstdio>
#include <vector>

using namespace gnarl::dsp;

namespace
{
    /** Frames kept for display. The table has 256; at display size you cannot
        distinguish that many, and 32 is enough for the stacked view to read as
        a morph. */
    constexpr int kDisplayFrames = 32;

    /** Harmonics kept. Beyond this a waveform's shape is set; the rest is
        detail no display can show. */
    constexpr int kDisplayHarmonics = 64;
}

int main (int argc, char* argv[])
{
    juce::ScopedJuceInitialiser_GUI juceInit;

    WavetableLibrary library;

    const auto frameSize = Wavetable::kBaseFrameSize;
    const auto order = static_cast<int> (std::log2 (static_cast<double> (frameSize)));

    juce::dsp::FFT fft (order);

    juce::MemoryOutputStream packed;

    for (int tableIndex = 0; tableIndex < WavetableLibrary::kNumFactoryTables; ++tableIndex)
    {
        const auto& table = library.getTable (tableIndex);

        for (int displayFrame = 0; displayFrame < kDisplayFrames; ++displayFrame)
        {
            const auto sourceFrame = juce::roundToInt (
                static_cast<double> (displayFrame) / (kDisplayFrames - 1)
                * (Wavetable::kNumFrames - 1));

            const auto* samples = table.getFrame (0, sourceFrame);

            std::vector<float> scratch (static_cast<std::size_t> (frameSize) * 2, 0.0f);

            for (int i = 0; i < frameSize; ++i)
                scratch[static_cast<std::size_t> (i)] = samples[i];

            fft.performRealOnlyForwardTransform (scratch.data(), true);

            // Normalised per frame, so quantisation spends its range on the
            // harmonics that are actually present. The display cares about
            // shape, not absolute level.
            auto peak = 0.0f;
            std::vector<float> magnitude (kDisplayHarmonics, 0.0f);
            std::vector<float> phase (kDisplayHarmonics, 0.0f);

            for (int h = 1; h <= kDisplayHarmonics; ++h)
            {
                const auto real = scratch[static_cast<std::size_t> (h) * 2];
                const auto imaginary = scratch[static_cast<std::size_t> (h) * 2 + 1];

                const auto index = static_cast<std::size_t> (h - 1);
                magnitude[index] = std::sqrt (real * real + imaginary * imaginary);
                phase[index] = std::atan2 (imaginary, real);

                peak = juce::jmax (peak, magnitude[index]);
            }

            const auto scale = peak > 0.0f ? 127.0f / peak : 0.0f;

            for (int h = 0; h < kDisplayHarmonics; ++h)
            {
                const auto index = static_cast<std::size_t> (h);

                const auto quantisedMagnitude = juce::jlimit (0, 127,
                    juce::roundToInt (magnitude[index] * scale));

                // Phase mapped from -pi..pi onto -127..127.
                const auto quantisedPhase = juce::jlimit (-127, 127,
                    juce::roundToInt (phase[index] / juce::MathConstants<float>::pi * 127.0f));

                packed.writeByte (static_cast<char> (quantisedMagnitude));
                packed.writeByte (static_cast<char> (quantisedPhase));
            }
        }

        std::printf ("  %-20s ok\n", WavetableLibrary::getTableName (tableIndex).toRawUTF8());
    }

    const auto base64 = juce::Base64::toBase64 (packed.getData(), packed.getDataSize());

    juce::String output;
    output << "/**\n"
           << " * Display spectra for the factory wavetables.\n"
           << " *\n"
           << " * GENERATED by tools/dump_wavetable_spectra.cpp - do not edit.\n"
           << " *\n"
           << " * Harmonics rather than samples, so the display can synthesise the waveform\n"
           << " * at whatever width its canvas is and redraw it when the warp changes.\n"
           << " * Analysed back out of the generated tables, so what is drawn is what the\n"
           << " * oscillator actually plays.\n"
           << " *\n"
           << " * Layout: " << WavetableLibrary::kNumFactoryTables << " tables x "
           << kDisplayFrames << " frames x " << kDisplayHarmonics
           << " harmonics, each harmonic a magnitude byte (0..127) followed by a\n"
           << " * phase byte (-127..127 mapping to -pi..pi).\n"
           << " *\n"
           << " * This is the FALLBACK, used by the browser preview and before the plugin\n"
           << " * has answered. In the plugin the live table is fetched over the bridge.\n"
           << " */\n\n"
           << "export const DISPLAY_TABLE_COUNT = " << WavetableLibrary::kNumFactoryTables << ";\n"
           << "export const DISPLAY_FRAME_COUNT = " << kDisplayFrames << ";\n"
           << "export const DISPLAY_HARMONIC_COUNT = " << kDisplayHarmonics << ";\n\n"
           << "export const DISPLAY_SPECTRA_BASE64 =\n  '" << base64 << "';\n";

    if (argc > 1)
    {
        juce::File file { juce::String (argv[1]) };
        file.replaceWithText (output);
        std::printf ("wrote %d bytes of spectra (%d base64 chars) to %s\n",
                     static_cast<int> (packed.getDataSize()),
                     base64.length(),
                     file.getFileName().toRawUTF8());
    }
    else
    {
        std::printf ("%d bytes packed\n", static_cast<int> (packed.getDataSize()));
    }

    return 0;
}
