#!/usr/bin/env python3
"""Writes icons/gnarl_*.svg into plugin/JuceLibraryCode/BinaryData.{h,cpp}.

BinaryData is generated by Projucer, which this repository cannot run - the
vendored JUCE is modules only. Until the CMake migration regenerates it from
the resource list, this rewrites the four logo entries in place: the array
body, the pointer's size in getNamedResource, and the size constant in the
header. Nothing else in the 2.2 MB file is touched.

Run after tools/make_logo.py.
"""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
CPP = ROOT / 'plugin/JuceLibraryCode/BinaryData.cpp'
HDR = ROOT / 'plugin/JuceLibraryCode/BinaryData.h'
ENTRIES = ['gnarl_ring_svg', 'gnarl_mark_svg', 'gnarl_word_svg', 'gnarl_word_ring_svg']

def cstr(b):
    out = []
    for ch in b:
        c = chr(ch)
        if c == '"': out.append('\\"')
        elif c == '\\': out.append('\\\\')
        elif c == '\n': out.append('\\n')
        elif 32 <= ch < 127: out.append(c)
        else: out.append(f'\\{ch:03o}')
    return '"' + ''.join(out) + '"'

cpp = CPP.read_text(encoding='utf-8', errors='surrogateescape')
hdr = HDR.read_text(encoding='utf-8', errors='surrogateescape')
for sym in ENTRIES:
    data = (ROOT / 'icons' / (sym[:-4] + '.svg')).read_bytes()
    m = re.search(r'const char\* %s = \(const char\*\) (temp_binary_data_\d+);' % sym, cpp)
    assert m, f'{sym} not declared in BinaryData.cpp'
    arr = m.group(1)
    pat = re.compile(r'(static const unsigned char %s\[\] =\n).*?(;\n)' % arr, re.S)
    assert pat.search(cpp), f'{arr} body not found'
    cpp = pat.sub(lambda mm: mm.group(1) + cstr(data) + mm.group(2), cpp, count=1)
    cpp = re.sub(r'(numBytes = )\d+(; return %s;)' % sym, r'\g<1>%d\g<2>' % len(data), cpp)
    hdr = re.sub(r'(const int\s+%sSize = )\d+;' % sym, r'\g<1>%d;' % len(data), hdr)
    print(f'{sym}: {len(data)} bytes <- icons/{sym[:-4]}.svg')
CPP.write_text(cpp, encoding='utf-8', errors='surrogateescape')
HDR.write_text(hdr, encoding='utf-8', errors='surrogateescape')
