#!/usr/bin/env python3
"""Writes icons/gnarl_*.svg into EVERY BinaryData.{h,cpp} in the repository.

BinaryData is generated by Projucer, which this repository cannot run - the
vendored JUCE is modules only. Until a CMake build regenerates it from the
resource list, this rewrites the four logo entries in place: the array
body, the pointer's name and its size in getNamedResource, the resource-name
lists, and the size constant in the header. Nothing else is touched.

EVERY BinaryData, not one. The plugin, the standalone app and the test
runner each have their own copy. The first version of this script updated
only the plugin's, so the standalone app kept Vital's logo bytes and stopped
compiling (paths.h asks for gnarl_* symbols it did not have) - unnoticed,
because CI built only the VST3.

Run after tools/make_logo.py.
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent

# old upstream symbol -> GNARL symbol, and the SVG each is made from
ENTRIES = [
    ('vital_ring_svg', 'gnarl_ring_svg', 'gnarl_ring.svg', 'vital_ring.svg'),
    ('vital_v_svg', 'gnarl_mark_svg', 'gnarl_mark.svg', 'vital_v.svg'),
    ('vital_word_svg', 'gnarl_word_svg', 'gnarl_word.svg', 'vital_word.svg'),
    ('vital_word_ring_svg', 'gnarl_word_ring_svg', 'gnarl_word_ring.svg', 'vital_word_ring.svg'),
]


def cstr(b):
    out = []
    for ch in b:
        c = chr(ch)
        if c == '"': out.append('\\"')
        elif c == '\\': out.append('\\\\')
        elif c == '\n': out.append('\\n')
        elif 32 <= ch < 127: out.append(c)
        else: out.append(f'\\{ch:03o}')
    return '"' + ''.join(out) + '"'


def embed(hdr_path):
    cpp_path = hdr_path.with_suffix('.cpp')
    hdr = hdr_path.read_text(encoding='utf-8', errors='surrogateescape')
    cpp = cpp_path.read_text(encoding='utf-8', errors='surrogateescape')
    touched = []
    for old, new, svg, old_file in ENTRIES:
        if old not in cpp and new not in cpp:
            continue
        # rename upstream's symbol (a no-op on files already converted); the
        # boundary keeps vital_word_svg from matching inside vital_word_ring_svg
        cpp = re.sub(r'\b%s(Size)?\b' % old, lambda m: new + (m.group(1) or ''), cpp)
        hdr = re.sub(r'\b%s(Size)?\b' % old, lambda m: new + (m.group(1) or ''), hdr)
        cpp = cpp.replace(f'"{old_file}"', f'"{svg}"')
        cpp = cpp.replace(f'//================== {old_file} ==================', f'//================== {svg} ==================')

        data = (ROOT / 'icons' / svg).read_bytes()
        m = re.search(r'const char\* %s = \(const char\*\) (temp_binary_data_\d+);' % new, cpp)
        assert m, f'{cpp_path}: {new} not declared'
        body = re.compile(r'(static const unsigned char %s\[\] =\n).*?(;\n)' % m.group(1), re.S)
        assert body.search(cpp), f'{cpp_path}: body of {m.group(1)} not found'
        cpp = body.sub(lambda mm: mm.group(1) + cstr(data) + mm.group(2), cpp, count=1)
        cpp = re.sub(r'(numBytes = )\d+(; return %s;)' % new, r'\g<1>%d\g<2>' % len(data), cpp)
        hdr = re.sub(r'(const int\s+%sSize = )\d+;' % new, r'\g<1>%d;' % len(data), hdr)
        touched.append(f'{new} {len(data)}B')
    hdr_path.write_text(hdr, encoding='utf-8', errors='surrogateescape')
    cpp_path.write_text(cpp, encoding='utf-8', errors='surrogateescape')
    return touched


if __name__ == '__main__':
    for hdr in sorted(ROOT.glob('*/JuceLibraryCode/BinaryData.h')):
        done = embed(hdr)
        print(f'{hdr.relative_to(ROOT)}: {", ".join(done) if done else "no logo entries"}')
